apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: NodePort
  selector:
    app: todo-app # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 30080 # This is the port exposed to the outside world. Value can be between 30000-32767
      protocol: TCP
      port: 1234 # This is a port that is available inside the cluster. Value can be ~ anything
      targetPort: 3000 # Port to where the request os going to be forwarded in the app